[package]
name = "ringline-redis"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
bytes = { workspace = true }
ketama = { workspace = true }
ringline = { workspace = true }
resp-proto = { workspace = true }
thiserror = { workspace = true }
