[package]
name = "protocol-memcache"
version = "0.3.8"
edition.workspace = true
license.workspace = true

[features]
default = ["ascii"]
ascii = []
binary = []
full = ["ascii", "binary"]

[dependencies]
memchr = { workspace = true }
itoa = { workspace = true }
thiserror = { workspace = true }
